export default {
    ADD_CATEGORY : "ADD_CATEGORY",
    START_ADD_CATEGORY: "START_ADD_CATEGORY",
    CANCEL_ADD_CATEGORY: "CANCEL_ADD_CATEGORY",
    START_DELETE_CATEGORY: "START_DELETE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    CANCEL_DELETE_CATEGORY: "CANCEL_DELETE_CATEGORY"
};